IF NOT EXISTS (SELECT * FROM sys.change_tracking_databases WHERE database_id = DB_ID(N'D:\PROJECTY PROGRAMOW\VISUAL STUDIO\MODYFIKACJATESTERA\TESTER_VFS169\DATABASE.MDF')) 
   ALTER DATABASE [D:\PROJECTY PROGRAMOW\VISUAL STUDIO\MODYFIKACJATESTERA\TESTER_VFS169\DATABASE.MDF] 
   SET  CHANGE_TRACKING = ON
GO
